// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jyiolhjkklytkjcmtzvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5aW9saGpra2x5dGtqY210enZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1ODEyODUsImV4cCI6MjA1NDE1NzI4NX0.gpCoy8vvp2cuP3pNwh6Lh_ImP71sR2wlPcpAUaZi0D0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);